### ISSUE TITLE
Encoding is broken in the css load from bookmarklet

### ISSUE THREAD

**Issue by a5e** [ffoodd/a11y.css#193] opened 2015-12-26 20:06 UTC
![encoding](https://cloud.githubusercontent.com/assets/1247692/12007779/6361b812-ac14-11e5-9110-8f570b38aa2f.png)

The one on the gh-pages seems good.

**Comment by ffoodd** [comment] 2015-12-27 18:41
It's fixed with [this commit](https://github.com/ffoodd/a11y.css/commit/dac4795c2805acf0b7b78f15c19a351420d26436).

It was caused by the Windows environment. Compiling on Linux is better ><

**Closed** 2015-12-27 18:42 UTC
Labels: bug
